# Generated by Django 5.0.6 on 2024-10-11 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game_Store', '0002_category_product_delete_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Game_Store.category')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='prices',
            field=models.ManyToManyField(related_name='products', to='Game_Store.price'),
        ),
    ]
