# Generated by Django 5.0.6 on 2024-10-11 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Game_Store', '0003_remove_product_price_price_product_prices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='price',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='prices',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Price',
        ),
    ]
